version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint-config-galex
    versions:
    - 2.15.0
    - 2.15.1
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.3
    - 12.7.1
    - 12.8.0
    - 13.0.0
    - 13.0.10
    - 13.0.7
    - 13.1.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.4
